spring.application.name=ai-agent

aws.region=${AWS_REGION}
aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.s3.originals-prefix=${S3_ORIGINALS_PREFIX}
aws.s3.results-prefix=${S3_RESULTS_PREFIX}
aws.s3.models-prefix=${S3_MODELS_PREFIX}
aws.s3.presigned-expires-seconds=${S3_PRESIGNED_EXPIRES_SECONDS}
